version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.41
    - 15.0.0
  - dependency-name: caniuse-lite
    versions:
    - 1.0.30001212
    - 1.0.30001214
    - 1.0.30001216
    - 1.0.30001218
  - dependency-name: sass
    versions:
    - 1.32.11
  - dependency-name: eslint-config-prettier
    versions:
    - 8.2.0
  - dependency-name: "@material-ui/styles"
    versions:
    - 5.0.0-alpha.29
    - 5.0.0-alpha.30
  - dependency-name: date-fns
    versions:
    - 2.20.1
    - 2.20.3
  - dependency-name: firebase
    versions:
    - 8.3.3
  - dependency-name: "@material-ui/core"
    versions:
    - 5.0.0-alpha.29
  - dependency-name: framer-motion
    versions:
    - 4.1.3
  - dependency-name: "@material-ui/lab"
    versions:
    - 5.0.0-alpha.29
